springdoc:
  cache:
    disabled: true  # false면 API 문서가 변경될 때마다 즉시 반영, 성능을 위해 true 처리
  default-consumes-media-type: application/json  # 기본 요청 미디어 타입
  default-produces-media-type: application/json  # 기본 응답 미디어 타입

---
spring:
  config:
    activate:
      on-profile: local

springdoc:
  swagger-ui:
    enabled: true
    path: /swagger-ui.html    # 접속 경로
    tags-sorter: alpha            # 태그 알파벳 정렬
    operations-sorter: method     # GET, POST, 등 정렬
    doc-expansion: none           # 태그 펼침 여부
  api-docs:
    enabled: true
    path: /api/v3/api-docs

---
spring:
  config:
    activate:
      on-profile: dev

springdoc:
  swagger-ui:
    enabled: true
    path: /api/swagger-ui.html    # 접속 경로
    tags-sorter: alpha            # 태그 알파벳 정렬
    operations-sorter: method     # GET, POST, 등 정렬
    doc-expansion: none           # 태그 펼침 여부
  api-docs:
    enabled: true
    path: /api/v3/api-docs

---
spring:
  config:
    activate:
      on-profile: prod

springdoc:
  swagger-ui:
    enabled: false
    path: /api/swagger-ui.html    # 접속 경로
    tags-sorter: alpha            # 태그 알파벳 정렬
    operations-sorter: method     # GET, POST, 등 정렬
    doc-expansion: none           # 태그 펼침 여부
  api-docs:
    enabled: false
    path: /api/v3/api-docs